import { DigitalService } from '../types/digitalSeva';

export const BUSINESS_INFO = {
  name: 'SHREE RADHE KRISHNA DIGITAL SERVICE',
  name_gu: 'શ્રી રાધે કૃષ્ણ ડિજિટલ સેવા',
  tagline_gu: 'તમારી ડિજિટલ સેવા, એક જ સ્થળે',
  tagline_en: 'Your Complete Digital Service, Under One Roof',
  email: 'khushidigitalseva11@gmail.com',
  address: 'Rudra Complex, Timberwa Road, Sadhli, Taluka Shinor, District Vadodara, Gujarat, India.',
  workingHours: 'Monday–Saturday: 9:00 AM–7:00 PM (Sunday Closed)',
  pvcDelivery: 'All India PVC Smart Card Home Delivery Available',
  domain: 'srkdigital.online',
};

export const INITIAL_SERVICES: DigitalService[] = [
  {
    id: 'srv-1',
    service_code: 'PAN',
    name: 'New PAN Card',
    name_gu: 'નવું PAN Card',
    price: 250,
    category: 'PAN Card',
    description: 'નવું PAN Card બનાવવા માટે ઓનલાઈન અરજી સહાય. 18 વર્ષથી વધુ ઉંમરના તમામ ભારતીય નાગરિકો માટે.',
    instructions: 'ઓરિજિનલ આધાર કાર્ડ અને સફેદ બેકગ્રાઉન્ડ વાળો પાસપોર્ટ ફોટો અને સફેદ કાગળ પર સહી અપલોડ કરો.',
    active: true,
    display_order: 1,
    required_documents: [
      { id: 'doc-pan-1', doc_code: 'AADHAAR', doc_name: 'Aadhaar Card (Front & Back)', doc_name_gu: 'આધાર કાર્ડ (આગળ અને પાછળ)', is_mandatory: true },
      { id: 'doc-pan-2', doc_code: 'PHOTO', doc_name: 'Passport Size Photo', doc_name_gu: 'પાસપોર્ટ સાઇઝ ફોટો', is_mandatory: true },
      { id: 'doc-pan-3', doc_code: 'SIGN', doc_name: 'Signature on White Paper', doc_name_gu: 'સફેદ કાગળ પર સહી', is_mandatory: true },
    ],
    form_fields: [
      { id: 'f-1', field_name: 'app_name', label: 'Full Name as per Aadhaar', label_gu: 'આધાર કાર્ડ મુજબ પૂરું નામ', field_type: 'text', is_required: true, display_order: 1 },
      { id: 'f-2', field_name: 'father_name', label: "Father's Full Name", label_gu: 'પિતાનું પૂરું નામ', field_type: 'text', is_required: true, display_order: 2 },
      { id: 'f-3', field_name: 'dob', label: 'Date of Birth', label_gu: 'જન્મ તારીખ', field_type: 'date', is_required: true, display_order: 3 },
      { id: 'f-4', field_name: 'app_mobile', label: 'Mobile Number', label_gu: 'મોબાઈલ નંબર', field_type: 'text', is_required: true, display_order: 4 },
      { id: 'f-5', field_name: 'gender', label: 'Gender', label_gu: 'જાતિ', field_type: 'dropdown', options: ['Male (પુરૂષ)', 'Female (સ્ત્રી)', 'Other'], is_required: true, display_order: 5 },
    ],
  },
  {
    id: 'srv-2',
    service_code: 'PANC',
    name: 'PAN Card Correction',
    name_gu: 'PAN Card સુધારો',
    price: 250,
    category: 'PAN Card',
    description: 'PAN Card માં નામ, પિતાનું નામ, જન્મ તારીખ, ફોટો અથવા સહી સુધારા માટે સંપૂર્ણ ઓનલાઈન સહાય.',
    instructions: 'હાલનું પાન કાર્ડ અને જે માહિતી સુધારવી હોય તેનો માન્ય સરકારી પુરાવો અપલોડ કરવો.',
    active: true,
    display_order: 2,
    required_documents: [
      { id: 'doc-panc-1', doc_code: 'EXISTING_PAN', doc_name: 'Existing PAN Card Copy', doc_name_gu: 'હાલનું PAN Card', is_mandatory: true },
      { id: 'doc-panc-2', doc_code: 'AADHAAR', doc_name: 'Aadhaar Card', doc_name_gu: 'આધાર કાર્ડ', is_mandatory: true },
      { id: 'doc-panc-3', doc_code: 'PROOF', doc_name: 'Proof of Correction (LC/Marksheet)', doc_name_gu: 'સુધારા અંગેનો પુરાવો (LC/માર્કશીટ)', is_mandatory: true },
    ],
    form_fields: [
      { id: 'f-panc-1', field_name: 'pan_number', label: 'Existing PAN Number', label_gu: 'હાલનો PAN નંબર', field_type: 'text', is_required: true, display_order: 1 },
      { id: 'f-panc-2', field_name: 'app_name', label: 'Correct Full Name', label_gu: 'સાચું પૂરું નામ', field_type: 'text', is_required: true, display_order: 2 },
      { id: 'f-panc-3', field_name: 'correction_type', label: 'What needs correction?', label_gu: 'શું સુધારો કરવાનો છે?', field_type: 'checkbox', options: ['Name (નામ)', 'DOB (જન્મ તારીખ)', 'Father Name (પિતાનું નામ)', 'Photo/Sign (ફોટો/સહી)'], is_required: true, display_order: 3 },
    ],
  },
  {
    id: 'srv-3',
    service_code: 'ENIR',
    name: 'e-Nirman Card',
    name_gu: 'ઈ-નિર્માણ કાર્ડ',
    price: 150,
    category: 'Government Scheme',
    description: 'ગુજરાત મકાન અને અન્ય બાંધકામ શ્રમયોગી કલ્યાણ બોર્ડ હેઠળ ઈ-નિર્માણ સ્માર્ટ કાર્ડ સહાય.',
    active: true,
    display_order: 3,
    required_documents: [
      { id: 'doc-enir-1', doc_code: 'AADHAAR', doc_name: 'Aadhaar Card', doc_name_gu: 'આધાર કાર્ડ', is_mandatory: true },
      { id: 'doc-enir-2', doc_code: 'PASSBOOK', doc_name: 'Bank Passbook / Cancelled Cheque', doc_name_gu: 'બેંક પાસબુક', is_mandatory: true },
      { id: 'doc-enir-3', doc_code: 'RATION', doc_name: 'Ration Card', doc_name_gu: 'રેશનકાર્ડ', is_mandatory: true },
      { id: 'doc-enir-4', doc_code: 'WORK_CERT', doc_name: '90 Days Construction Work Certificate', doc_name_gu: '90 દિવસ કામ કર્યાનું પ્રમાણપત્ર', is_mandatory: true },
    ],
  },
  {
    id: 'srv-4',
    service_code: 'KMM',
    name: 'Kuvarbai nu Mameru',
    name_gu: 'કુંવરબાઈનું મામેરું યોજના',
    price: 250,
    category: 'Government Scheme',
    description: 'દીકરીના લગ્ન પ્રસંગે સરકારી ₹12,000 ની નાણાકીય સહાય માટે ઓનલાઈન ઈ-સમાજ કલ્યાણ અરજી.',
    active: true,
    display_order: 4,
    required_documents: [
      { id: 'doc-kmm-1', doc_code: 'MARRIAGE_CERT', doc_name: 'Marriage Certificate', doc_name_gu: 'લગ્ન નોંધણી પ્રમાણપત્ર', is_mandatory: true },
      { id: 'doc-kmm-2', doc_code: 'DAUGHTER_AADHAAR', doc_name: 'Daughter Aadhaar', doc_name_gu: 'દીકરીનું આધાર કાર્ડ', is_mandatory: true },
      { id: 'doc-kmm-3', doc_code: 'FATHER_AADHAAR', doc_name: 'Father / Guardian Aadhaar', doc_name_gu: 'પિતાનું આધાર કાર્ડ', is_mandatory: true },
      { id: 'doc-kmm-4', doc_code: 'INCOME_CERT', doc_name: 'Income Certificate', doc_name_gu: 'આવકનો દાખલો', is_mandatory: true },
      { id: 'doc-kmm-5', doc_code: 'BANK_PASSBOOK', doc_name: 'Daughter Bank Passbook', doc_name_gu: 'દીકરીની બેંક પાસબુક', is_mandatory: true },
    ],
  },
  {
    id: 'srv-5',
    service_code: 'AYU',
    name: 'New Ayushman Card',
    name_gu: 'નવું આયુષ્માન કાર્ડ',
    price: 150,
    category: 'Health',
    description: 'PMJAY આયુષ્માન ભારત કાર્ડ દ્વારા પરિવારોને વાર્ષિક ₹5 થી ₹10 લાખ સુધીની કેશલેસ હોસ્પિટલ સારવાર.',
    active: true,
    display_order: 5,
    required_documents: [
      { id: 'doc-ayu-1', doc_code: 'RATION', doc_name: 'Ration Card', doc_name_gu: 'રેશનકાર્ડ', is_mandatory: true },
      { id: 'doc-ayu-2', doc_code: 'FAMILY_AADHAAR', doc_name: 'Family Members Aadhaar', doc_name_gu: 'તમામ સભ્યોના આધાર કાર્ડ', is_mandatory: true },
    ],
  },
  {
    id: 'srv-6',
    service_code: 'AYUK',
    name: 'Ayushman Update / KYC',
    name_gu: 'આયુષ્માન Card Update / KYC',
    price: 50,
    category: 'Health',
    description: 'હાલના આયુષ્માન કાર્ડમાં e-KYC બાયોમેટ્રિક/OTP વેરિફિકેશન, નવો સભ્ય ઉમેરવો કે ફોટો અપડેટ.',
    active: true,
    display_order: 6,
  },
  {
    id: 'srv-7',
    service_code: 'PMK',
    name: 'PM-Kisan Assistance',
    name_gu: 'PM કિસાન સહાય',
    price: 250,
    category: 'Farmer',
    description: 'પ્રધાનમંત્રી કિસાન સન્માન નિધિ યોજના અંતર્ગત ખેડૂતોને વાર્ષિક ₹6,000 નવી સહાય અરજી.',
    active: true,
    display_order: 7,
    required_documents: [
      { id: 'doc-pmk-1', doc_code: 'LAND_712', doc_name: '7/12 & 8-A Land Record', doc_name_gu: 'જમીન 7/12 અને 8-અ નકલ', is_mandatory: true },
      { id: 'doc-pmk-2', doc_code: 'AADHAAR', doc_name: 'Farmer Aadhaar Card', doc_name_gu: 'ખેડૂતનું આધાર કાર્ડ', is_mandatory: true },
      { id: 'doc-pmk-3', doc_code: 'PASSBOOK', doc_name: 'Bank Passbook', doc_name_gu: 'બેંક પાસબુક', is_mandatory: true },
    ],
  },
  {
    id: 'srv-8',
    service_code: 'PMKK',
    name: 'PM-Kisan KYC',
    name_gu: 'PM કિસાન KYC',
    price: 50,
    category: 'Farmer',
    description: 'PM Kisan યોજનાના હપ્તા સરળતાથી ખાતામાં જમા રાખવા માટે જરૂરી e-KYC પૂર્ણ કરવાની સહાય.',
    active: true,
    display_order: 8,
  },
  {
    id: 'srv-9',
    service_code: 'LAND',
    name: 'Land Information / PDF',
    name_gu: 'જમીનની માહિતી / PDF',
    price: 10,
    category: 'Land',
    description: 'AnyRoR પોર્ટલ પરથી 7/12, 8-A, હકપત્રક નોંધ 6 ની સત્તાવાર કલર PDF નકલ ડાઉનલોડ.',
    active: true,
    display_order: 9,
  },
  {
    id: 'srv-10',
    service_code: 'INC',
    name: 'Income Certificate',
    name_gu: 'આવકનો દાખલો',
    price: 250,
    category: 'Certificate',
    description: 'મામલતદાર / તાલુકા પંચાયત કચેરી માન્ય 3 વર્ષની મુદત ધરાવતો ડિજિટલ સહી વાળો આવકનો દાખલો.',
    active: true,
    display_order: 10,
    required_documents: [
      { id: 'doc-inc-1', doc_code: 'RATION', doc_name: 'Ration Card', doc_name_gu: 'રેશનકાર્ડ', is_mandatory: true },
      { id: 'doc-inc-2', doc_code: 'LIGHT_BILL', doc_name: 'Electricity Bill', doc_name_gu: 'લાઇટબિલ', is_mandatory: true },
      { id: 'doc-inc-3', doc_code: 'TALATI_REPORT', doc_name: 'Talati Panchnama / Income Proof', doc_name_gu: 'તલાટી રૂબરૂ પંચનામું', is_mandatory: true },
      { id: 'doc-inc-4', doc_code: 'AADHAAR', doc_name: 'Aadhaar Card', doc_name_gu: 'આધાર કાર્ડ', is_mandatory: true },
    ],
  },
  {
    id: 'srv-11',
    service_code: 'PF',
    name: 'PF Online Services',
    name_gu: 'PF Online Services',
    price: 250,
    category: 'PF',
    description: 'PF પીએફ ઉપાડ, એડવાન્સ બીમારી કે ઘર ખર્ચ ક્લેમ, KYC અપડેટ, UAN એક્ટિવેશન અને પાસબુક સહાય.',
    active: true,
    display_order: 11,
  },
  {
    id: 'srv-12',
    service_code: 'FARM',
    name: 'Farmer Registration',
    name_gu: 'ખેડૂત નોંધણી',
    price: 150,
    category: 'Farmer',
    description: 'i-Khedut પોર્ટલ પર સરકારી સાધન સહાય, દવા છંટકાવ પંપ, તાર ફેન્સિંગ અને પાક નોંધણી.',
    active: true,
    display_order: 12,
  },
  {
    id: 'srv-13',
    service_code: 'MPAN',
    name: 'Minor PAN Card',
    name_gu: 'Minor PAN Card',
    price: 250,
    category: 'PAN Card',
    description: '18 વર્ષથી ઓછી ઉંમરના બાળકો માટે PAN Card બનાવવા માટે ઓનલાઈન સહાય.',
    active: true,
    display_order: 13,
  },
  {
    id: 'srv-14',
    service_code: 'VOTER',
    name: 'New Voter Card',
    name_gu: 'નવું ચૂંટણી કાર્ડ',
    price: 150,
    category: 'Voter',
    description: 'મતદાર યાદીમાં નવું નામ ઉમેરવા ફોર્મ-6 ઓનલાઇન અરજી અને નવું Voter ID Card.',
    active: true,
    display_order: 14,
  },
  {
    id: 'srv-15',
    service_code: 'VOTERC',
    name: 'Voter Card Correction',
    name_gu: 'ચૂંટણી કાર્ડ સુધારો',
    price: 150,
    category: 'Voter',
    description: 'ચૂંટણી કાર્ડમાં નામ, અટક, સરનામું કે ફોટો સુધારવા માટે ફોર્મ-8 અરજી.',
    active: true,
    display_order: 15,
  },
  {
    id: 'srv-16',
    service_code: 'ITR',
    name: 'Income Tax Return',
    name_gu: 'Income Tax Return',
    price: 2500,
    category: 'Income Tax',
    description: 'ITR-1 / ITR-2 ઇન્કમટેક્સ રિટર્ન ફાઈલિંગ, TDS રિફંડ અને કર મુક્તિ સલાહ સહાય.',
    active: true,
    display_order: 16,
  },
  {
    id: 'srv-17',
    service_code: 'ESHRAM',
    name: 'e-Shram Card',
    name_gu: 'ઈ-શ્રમ કાર્ડ',
    price: 150,
    category: 'Government Scheme',
    description: 'અસંગઠિત ક્ષેત્રના શ્રમિકો માટે ભારત સરકારનું ઈ-શ્રમ કાર્ડ, ₹2 લાખ અકસ્માત વીમા સુરક્ષા.',
    active: true,
    display_order: 17,
  },
  {
    id: 'srv-18',
    service_code: 'UDYAM',
    name: 'Udyam Registration',
    name_gu: 'Udyam Registration',
    price: 200,
    category: 'Business',
    description: 'સૂક્ષ્મ, લઘુ અને મધ્યમ ઉદ્યોગો (MSME) માટે ઉદ્યમ આધાર પ્રમાણપત્ર રજિસ્ટ્રેશન.',
    active: true,
    display_order: 18,
  },
  {
    id: 'srv-19',
    service_code: 'NOC',
    name: 'Police Verification / NOC',
    name_gu: 'પોલીસ વેરિફિકેશન (NOC)',
    price: 150,
    category: 'Police',
    description: 'ખાનગી નોકરી, પાસપોર્ટ કે ભાડુઆત વેરિફિકેશન માટે પોલીસ ક્લિયરન્સ સર્ટિફિકેટ સહાય.',
    active: true,
    display_order: 19,
  },
  {
    id: 'srv-20',
    service_code: 'ABHA',
    name: 'ABHA Card',
    name_gu: 'ABHA Card',
    price: 150,
    category: 'Health',
    description: 'આયુષ્માન ભારત ડિજિટલ મિશન હેઠળ 14 અંકનું હેલ્થ એકાઉન્ટ ABHA કાર્ડ જનરેશન.',
    active: true,
    display_order: 20,
  },
  {
    id: 'srv-21',
    service_code: 'PVC',
    name: 'PVC Card Printing',
    name_gu: 'PVC Card Printing',
    price: 150,
    category: 'Printing',
    description: 'Aadhaar, PAN, Voter, Ayushman કે કોઈપણ કાર્ડની ઓલ ઇન્ડિયા હાઇ-ક્વોલિટી PVC સ્માર્ટ કાર્ડ પ્રિન્ટિંગ અને હોમ ડિલિવરી.',
    active: true,
    display_order: 21,
    required_documents: [
      { id: 'doc-pvc-1', doc_code: 'PDF_CARD', doc_name: 'Card PDF File', doc_name_gu: 'કાર્ડની ઓરિજિનલ PDF ફાઈલ', is_mandatory: true },
    ],
    form_fields: [
      { id: 'f-pvc-1', field_name: 'delivery_name', label: 'Recipient Full Name', label_gu: 'મેળવનારનું પૂરું નામ', field_type: 'text', is_required: true, display_order: 1 },
      { id: 'f-pvc-2', field_name: 'delivery_mobile', label: 'Delivery Mobile Number', label_gu: 'ડિલિવરી મોબાઈલ નંબર', field_type: 'text', is_required: true, display_order: 2 },
      { id: 'f-pvc-3', field_name: 'delivery_address', label: 'Full Postal Address with Pincode', label_gu: 'પૂરું સરનામું અને પિનકોડ', field_type: 'textarea', is_required: true, display_order: 3 },
    ],
  },
];
